name : flair
channels : 
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies :
  - python==3.10
  - albumentations
  - matplotlib
  - numpy
  - omegaconf
  - pandas
  - Pillow
  - pytorch-cuda==11.7
  - pytorch-lightning==1.9.5
  - PyYAML
  - rasterio
  - rich
  - scikit-image
  - scikit-learn
  - segmentation-models-pytorch
  - torchmetrics==0.9.2
  - torchvision
  - tensorboard
  - jupyter

